spring:
  application:
    name: api-gateway

  cloud:
    openfeign:
      client:
        config:
          database-provider:
            url: http://${DEV_ENV_HOST}:8081
          notification-service:
            url: http://${DEV_ENV_HOST}:8083

server:
  port: 8082

feign:
  data-provider-api:
    base-path: /api/data-provider/security
    endpoints:
      register: /register
      login: /login
      get-user-info: /info
      update-username: /update-username
      update-user-photo: /update-user-photo
      get-user-by-email: /by-email
      save-verification-code: /save-verification-code
      check-verified: /check-verified
      get-verification-code: /get-verification-code
      update-verification-status: /update-verification-status
  notification-service-api:
    base-path: /api/notification-service/mail
    endpoints:
      send-email: /send-mail

jwt:
  secret: {JWT_SECRET}