spring:
  application:
    name: api-gateway

  cloud:
    openfeign:
      client:
        config:
          database-provider:
            url: http://${DEV_ENV_HOST}:8081

server:
  port: 8082

feign:
  user-api:
    base-path: /api/route-provider/security
    endpoints:
      register: /register
      login: /login
      get-user-info: /info
      update-username: /update-username
      get-user-by-email: /by-email

jwt:
  secret: {JWT_SECRET}