const val USER_BASE_PATH_URL = "/api/security-service/security"
const val REGISTER_URL = "/register"
const val LOGIN_URL = "/login"
const val GET_USER_INFO_URL = "/getUserInfo"
const val UPDATE_USERNAME_URL = "/updateUsername"