name: Build

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
        env:
          DEV_ENV_HOST_DATA: localhost
          DEV_ENV_HOST_NOTIFICATION: localhost
          JWT_SECRET: bXktc3VwZXItc2VjdXJlLWFuZC1sb25nLXNlY3JldC1rZXktMTIzNDU2 # it's REALLY my secret key I hope you are going to use it
          JWT_EXPIRATION: 3600
